services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ****
      MYSQL_DATABASE: testDB
      MYSQL_USER: test
      MYSQL_PASSWORD: ****
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # optional: run SQL on startup
    networks:
      - db_network

volumes:
  mysql_data:

networks:
  db_network:
    driver: bridge